### PR TITLE
Add decompression into numpy arrays

### PR DESCRIPTION
**Pull request by sk1p**
Vendor the `bitshuffle` code and generate a rust+Python binding. This means we don't need to separately install the `bitshuffle` Python package anymore.

### CODE REVIEW

**Comment by uellue** [comment]
`pytest tests/detectors/dectris` with test data hangs on Windows, Python 3.9 with this version and https://github.com/LiberTEM/LiberTEM-live/pull/57/. With the released version and the LiberTEM-live master the tests pass.

**Comment by sk1p** [comment]
Probably a good idea to remove any obvious panic-causes (`unwrap`s), as windows really doesn't like the worker processes to "go away".

**Comment by uellue** [comment]
> `pytest tests/detectors/dectris` with test data hangs on Windows, Python 3.9 with this version and [LiberTEM/LiberTEM-live#57](https://github.com/LiberTEM/LiberTEM-live/pull/57). With the released version and the LiberTEM-live master the tests pass.

Fix confirmed for 9c1beaa

**Comment by sk1p** [comment]
Can't reproduce this issue locally, logged it upstream for now: https://github.com/PyO3/maturin-action/issues/99

**Pull request merged**
